# Generated by Django 5.0.7 on 2024-07-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_mob', models.IntegerField()),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_working', models.BooleanField(default=True)),
                ('emp_department', models.CharField(max_length=20)),
            ],
        ),
    ]
