# Generated by Django 5.0.7 on 2024-07-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_mob',
            field=models.CharField(max_length=10),
        ),
    ]
