# Generated by Django 5.0.7 on 2024-07-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_alter_employee_emp_mob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_mob',
            new_name='mob',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_working',
            new_name='working',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
