# Generated by Django 5.0.7 on 2024-07-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_rename_emp_address_employee_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mob',
            new_name='contact',
        ),
    ]
