# Generated by Django 5.0.7 on 2024-07-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_rename_id_employee_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
